### ISSUE TITLE
tutorial pls

### ISSUE THREAD

**Issue by DraidS** [Firebladedoge229/Mintstrap#1]
how do i use this

**Comment by DraidS** [comment]
no entiendo

**Comment by Firebladedoge229** [comment]
https://github.com/Firebladedoge229/Mintstrap/blob/main/README.md

**Comment by DraidS** [comment]
fix it pls

**Comment by DraidS** [comment]
i cannot install bloxstrap

**Comment by DraidS** [comment]
bloxstrap exception
